version: '2'
services:
  nats:
    container_name: nats
    command: -cid=STAN -m 8222
    image: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"
  nats-tools:
    container_name: nats-tools
    build: .
    image: nats-tools
  nkb:
    container_name: nkb
    build: ./nkb
    image: nkb
    depends_on:
      - nats
      - kafka
    command: "-ns nats -ks kafka:9092"
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "foo:1:1, bar:1:1, test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
