name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Install tools
      run: make install-tools
    - name: Lint
      run: make lint
    - name: Release
      shell: bash --noprofile --norc -x -eo pipefail {0}
      env:
        GO111MODULE: 'on'
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        export GOPATH="$RUNNER_WORKSPACE"
        curl --location http://git.io/goreleaser | bash
