name: Testing

on:
- push
- pull_request

jobs:
  build:
    name: Testing Job
    runs-on: ubuntu-18.04
    steps:
    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Install tools
      run: make update
    - name: Test
      run: make test
