name: Testing

on:
- push
- pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        go-version: 1.19.x
    - name: Install tools
      run: make install-tools
    - name: Lint
      run: make lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    - name: Test and upload coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: make test-codecov
